name: json_path
version: 0.3.0
description: Implementation of JSONPath expressions like "$.store.book[2].price". Reads and writes values in parsed JSON objects.
homepage: "https://github.com/f3ath/jessie"

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  rfc_6901: ^0.1.0
  petitparser: ^4.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.0
  path: ^1.8.1
  check_coverage: ^0.0.2

