name: json_path
version: 0.0.1
description: JSONPath for Dart. JSONPath is XPath for JSON. It is a path in a JSON document.
homepage: "https://github.com/f3ath/jessie"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.0

environment:
  sdk: ">=2.8.0 <3.0.0"
