name: json_path
version: 0.7.4
description: "Implementation of RFC 9535 - JSONPath: Query Expressions for JSON. Reads and writes values in parsed JSON objects using queries like `$.store.book[2].price`."
homepage: "https://github.com/f3ath/jessie"

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  iregexp: ^0.1.2
  maybe_just_nothing: ^0.5.2
  petitparser: ^6.0.1
  rfc_6901: ^0.2.0

dev_dependencies:
  check_coverage: ^0.0.4
  lints: ^4.0.0
  path: ^1.8.2
  test: ^1.21.1

cider:
  link_template:
    tag: https://github.com/f3ath/jessie/releases/tag/%tag%
    diff: https://github.com/f3ath/jessie/compare/%from%...%to%
