name: json_path
version: 0.1.1+1
description: Implementation of JSONPath expressions like "$.store.book[2].price". Can read and set values in parsed JSON objects.
homepage: "https://github.com/f3ath/jessie"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.0
  test_coverage: ^0.4.3

environment:
  sdk: ">=2.8.0 <3.0.0"
